services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: garden
      MARIADB_USER: gardenuser
      MARIADB_PASSWORD: gardenpass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

  backend:
    build: .
    depends_on:
      - db
    env_file: .env
