import type { Metadata } from "next";
import Providers from "../providers";
import "../globals.css";
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: "Garden Map",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;

  let messages;
  try {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error('Failed to load messages for locale', locale, error);
    notFound();
  }


  return (
    <html lang={locale} className="bg-background text-foreground">
      <body className="font-sans antialiased bg-background text-foreground">
        <NextIntlClientProvider locale={locale} >
          <Providers>
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}